### ISSUE TITLE
Misplace in AddWorkFragment

### ISSUE THREAD

**Issue by tejaslodaya** [david-zhou/UberClone#2]
AddWorkFragment.java
Please check line number 183. The button click should be on R.id.remove_work_button, rather than R.id.remove_home_button. Cheers!
And the auto-suggestion isnt working.Tried on another code using custom AutoCompleteTextView class. Is something wrong with my API_KEY? I got my api key by following steps:-

1) Went to console.developers.google.com and created a project.
2)Added the PLACES API and maps API to the project
3) Went over to Credentials tab and generated a client id.
4) Went to the app and got the SHA1 certificate code.Pasted it in the box they have provided.Pasted the package name too.

Key for Android applications:
API key 
XXXX
Android applications  
SHA1 KEY;com.dzt.uberclone
SHA1 KEY;com.dzt.uberdriver
Activation date 
Jun 27, 2015, 9:01:00 PM
Activated by  
xx@gmail.com (you)

Is it the correct way to obtain it?

**Comment by david-zhou** [comment]
You are right, messed up a little with the copy paste on the AddWorkFragment, it should be fine now

Make sure you are using Google Places API Web Service and NOT the Android one.
Hope it helps!

**Comment by tejaslodaya** [comment]
Thanks a ton! Worked. Your app is awesome! Thank you!
And keep updating the app.
It would be grateful to build my startup.
Cheers!

**Comment by david-zhou** [comment]
Thanks!

I'm glad I could help
